import {API,mlb,type RawGame} from '@/lib/mlb';
import {levels,validateAssignments,type Game,type Assignment,type Injury,type Transaction} from '@/lib/report';
import {gameLogAssignments,injuryPeriods,mergeAssignmentSources,rosterAssignments,type Entry} from '@/lib/roster';
export const dynamic='force-dynamic';
export const maxDuration=60;
type ReportRequest={mode:'player'|'team';season:number;playerId?:number;label?:string;teamSchedule?:boolean;assignments?:unknown;workpaper?:{clientReference?:string;preparedBy?:string;notes?:string}};
export async function POST(request:Request){
 let body:ReportRequest;let assignments:Assignment[]=[];
 try{body=await request.json() as ReportRequest;if(!Number.isInteger(body.season)||body.season<1900||body.season>new Date().getFullYear()+1)throw new Error('Choose a valid season.');if(body.mode==='player'){if(!Number.isInteger(body.playerId)||!body.playerId||body.playerId<1)throw new Error('Choose a player.');}else{assignments=validateAssignments(body.assignments);if(assignments.some(a=>+a.start.slice(0,4)!==body.season))throw new Error('Assignment dates must match the season.');}}
 catch(e){return Response.json({error:e instanceof Error?e.message:'Invalid request.'},{status:400});}
 const sources:string[]=[];const warnings:string[]=[];const games:Game[]=[];const springGames:Game[]=[];let injuries:Injury[]=[];let transactions:Transaction[]=[];let excluded=0;
 const today=new Date().toISOString().slice(0,10);const through=today<`${body.season}-12-31`?today:`${body.season}-12-31`;
 async function read(path:string){sources.push(API+path);return mlb(path);}
 try{
  if(body.mode==='player'){
   const [personData,transactionData,...directories]=await Promise.all([read(`/people/${body.playerId}?hydrate=rosterEntries`),read(`/transactions?playerId=${body.playerId}&startDate=${body.season-2}-01-01&endDate=${body.season}-12-31`),...Object.keys(levels).map(id=>read(`/teams?sportId=${id}&season=${body.season}`))]);
   transactions=(transactionData.transactions??[]) as Transaction[];
   const teams=new Map<number,{sportId:number;name:string}>();Object.keys(levels).forEach((id,i)=>{for(const t of directories[i].teams??[])teams.set(t.id,{sportId:+id,name:t.name});});
   const entries=(personData.people?.[0]?.rosterEntries??[]) as Entry[];
   const rosterRows=rosterAssignments(entries,transactions,teams,body.season,through);const logResults=await Promise.allSettled(['hitting','pitching'].map(group=>read(`/stats?${new URLSearchParams({stats:'gameLog',group,season:String(body.season),sportIds:Object.keys(levels).join(','),personId:String(body.playerId),limit:'1000'})}`)));const logResponses=logResults.filter((item):item is PromiseFulfilledResult<any>=>item.status==='fulfilled').map(item=>item.value);assignments=mergeAssignmentSources(rosterRows,gameLogAssignments(logResponses,teams),body.season,through);for(const t of transactions){const date=(t.effectiveDate??t.date).slice(0,10),source=t.fromTeam,prior=new Date(Date.parse(date)-86400000).toISOString().slice(0,10);if(date>`${body.season}-01-01`&&date<=through&&source&&/optioned|assigned|outright|traded/i.test(t.description)&&!assignments.some(a=>a.teamId===source.id&&a.start<=prior&&a.end>=prior)){const team=teams.get(source.id),earlier=assignments.filter(a=>a.teamId===source.id&&a.end<date).map(a=>a.end).sort().at(-1),start=earlier?new Date(Date.parse(earlier)+86400000).toISOString().slice(0,10):`${body.season}-01-01`;assignments.push({teamId:source.id,teamName:team?.name??source.name,sportId:team?.sportId??1,start,end:prior,rosterStatus:'Manual review'});}}assignments.sort((a,b)=>a.start.localeCompare(b.start));injuries=injuryPeriods(transactions,body.season,through);const seasonFirst=`${body.season}-01-01`;injuries=injuries.filter(injury=>{const activeEntry=entries.some(e=>e.team.id===injury.teamId&&(e.startDate??'9999')<=through&&(e.endDate??through)>=seasonFirst&&!/injured|disabled/i.test(e.status?.description??''));const newSeasonIl=transactions.some(t=>(t.effectiveDate??t.date).slice(0,10)>=seasonFirst&&(t.toTeam??t.fromTeam)?.id===injury.teamId&&/(placed|transferred).* (injured|disabled) list/i.test(t.description));return !(injury.open&&injury.start===seasonFirst&&activeEntry&&!newSeasonIl);});
   // A current IL status can identify an otherwise missing transaction, but is never backdated to the original signing date.
   for(const e of entries){if((!e.endDate||e.endDate>=through)&&e.startDate&&e.startDate<=through&&e.statusDate&&e.statusDate<=through&&e.status?.description&&/injured|disabled/i.test(e.status.description)&&teams.has(e.team.id)&&!injuries.some(i=>i.teamId===e.team.id&&i.start<=e.statusDate!&&i.end>=e.statusDate!))injuries.push({teamId:e.team.id,team:e.team.name,start:e.statusDate<`${body.season}-01-01`?`${body.season}-01-01`:e.statusDate,end:through,status:`${e.status.description} — current roster status; verify start and end`,open:true});}
   warnings.push('Automatic roster reconstruction is a draft: roster entries can represent organizational or 40-man membership, and transactions may omit or ambiguously describe assignments. Review the roster timeline and transactions, especially promotions, trades, and rehab. Reconcile assignment boundaries against client records.');
   warnings.push('Injured-list (IL / IR) periods are outlined separately. Games during IL are the team’s locations, not the player’s rehabilitation or physical location. No appearance is required for inclusion.');
   if(!assignments.length)warnings.push('No supported dated roster assignments were found. Verify against client records; this does not mean the player was not rostered.');
  }
  if(body.mode!=='player')injuries=assignments.filter(a=>a.rosterStatus==='Injured list').map(a=>({teamId:a.teamId,team:a.teamName,start:a.start,end:a.end,status:'User-entered injured-list period',open:false}));
  await Promise.all(assignments.map(async a=>{const path=`/schedule?${new URLSearchParams({sportId:String(a.sportId),teamId:String(a.teamId),startDate:a.start,endDate:a.end,hydrate:'venue(location)'})}`;const data=await read(path);const scheduled=(data.dates??[]).flatMap((d:{games:RawGame[]})=>d.games??[]);const regular=scheduled.filter((g:RawGame)=>g.gameType==='R').map((g:RawGame)=>g.officialDate).sort();const regularStart=regular[0]??`${body.season}-04-01`;const regularEnd=regular.at(-1)??`${body.season}-09-30`;
   for(const d of data.dates??[])for(const g of d.games as RawGame[]){if(g.officialDate<a.start||g.officialDate>a.end||(g.gameType==='E'&&(g.officialDate<regularStart||g.officialDate>regularEnd)))continue;if(g.status.abstractGameState!=='Final'){excluded++;continue;}const home=g.teams.home.team.id===a.teamId;if(!home&&g.teams.away.team.id!==a.teamId)continue;const loc=g.venue?.location;const review:string[]=[];const injury=injuries.find(i=>i.teamId===a.teamId&&i.start<=g.officialDate&&i.end>=g.officialDate);const rosterStatus=body.teamSchedule?'Team schedule':injury?'Injured list':a.rosterStatus??'User-entered roster assignment';
   if(!loc?.city||!loc?.state||!loc?.country)review.push('Incomplete venue location');if(g.resumeDate||g.resumedFrom||/suspend|complet/i.test(g.status.detailedState))review.push('Resumed game: verify actual dates');if(g.rescheduledFrom)review.push('Rescheduled game');if(injury)review.push('IL: player location unknown; team location only');if(body.mode==='player')review.push('Verify reconstructed roster membership');
   const row={id:g.gamePk,date:g.officialDate,team:(home?g.teams.home:g.teams.away).team.name,opponent:(home?g.teams.away:g.teams.home).team.name,level:levels[a.sportId],venue:g.venue?.name??'Unknown',city:loc?.city??'Unknown',state:loc?.state??'Unknown',country:loc?.country??'Unknown',homeAway:home?'Home' as const:'Away' as const,status:g.status.detailedState,type:g.gameType,review:review.join('; '),source:API+path,rosterStatus};
   (g.gameType==='S'?springGames:games).push(row);}
  }));
  if(body.mode==='player'){
   const path=`/schedule?${new URLSearchParams({sportId:'1',startDate:`${body.season}-01-01`,endDate:through,gameTypes:'A',hydrate:'venue(location)'})}`;const data=await read(path);const allStar=(data.dates??[]).flatMap((d:{games:RawGame[]})=>d.games??[]).filter((g:RawGame)=>g.status.abstractGameState==='Final');
   const appearances=await Promise.all(allStar.map(async(g:RawGame)=>{const box=await read(`/game/${g.gamePk}/boxscore`);for(const side of ['home','away'] as const){const club=box.teams?.[side]??{};const participants=new Set<number>([...(club.batters??[]),...(club.pitchers??[])]);if(!participants.has(body.playerId!))continue;const opponent=side==='home'?'away':'home';const loc=g.venue?.location;return {id:g.gamePk,date:g.officialDate,team:g.teams[side].team.name,opponent:g.teams[opponent].team.name,level:'MLB',venue:g.venue?.name??'Unknown',city:loc?.city??'Unknown',state:loc?.state??'Unknown',country:loc?.country??'Unknown',homeAway:side==='home'?'Home':'Away',status:g.status.detailedState,type:'A',review:'',source:API+path,rosterStatus:'All-Star appearance'} as Game;}return null;}));games.push(...appearances.filter((g):g is Game=>g!==null));
  }
  warnings.push('Game dates are official provider dates. Suspended games may span several dates. Off-days, travel, workouts, and actual player presence are not inferred. Jurisdiction totals include team games during IL and are not taxable duty-day totals.');
  const unique=[...new Map(games.map(g=>[`${g.id}|${g.team}`,g])).values()].sort((a,b)=>a.date.localeCompare(b.date)||a.id-b.id);const uniqueSpring=[...new Map(springGames.map(g=>[`${g.id}|${g.team}`,g])).values()].sort((a,b)=>a.date.localeCompare(b.date)||a.id-b.id);
  return Response.json({teamSchedule:body.mode==='team'&&body.teamSchedule===true,games:unique,springGames:uniqueSpring,profileUrl:body.mode==='player'?`${assignments.some(a=>a.sportId===1)?'https://www.mlb.com':'https://www.milb.com'}/player/${body.playerId}`:undefined,excluded,retrievedAt:new Date().toISOString(),cutoff:through,basis:body.mode==='player'?'Draft roster-based team locations · review required':'Team locations within user-entered roster periods',label:String(body.label??'Roster report').slice(0,150),season:body.season,workpaper:{clientReference:String(body.workpaper?.clientReference??'').slice(0,100),preparedBy:String(body.workpaper?.preparedBy??'').slice(0,100),notes:String(body.workpaper?.notes??'').slice(0,4000)},sources,warnings,assignments,injuries,transactions:transactions.filter(t=>(t.effectiveDate??t.date).slice(0,4)===String(body.season))},{headers:{'Cache-Control':'no-store'}});
 }catch{return Response.json({error:'The provider could not complete this report. No partial report was produced. Try again.'},{status:502});}
}
