'use client';
import {useState} from 'react';
import {levels,summarize,type Report} from '@/lib/report';

type Team={id:number;name:string;sportId:number;level:string;league:string;parentOrgId?:number|null};
type Player={id:number;name:string;birthDate?:string;position:string};
async function getJson(url:string,init?:RequestInit){const response=await fetch(url,{...init,cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.error??'Request failed.');return data;}

export default function Home(){
 const [mode,setMode]=useState<'player'|'team'>('player');
 const [season,setSeason]=useState(2026);const [busy,setBusy]=useState('');const [error,setError]=useState('');
 const [query,setQuery]=useState('');const [players,setPlayers]=useState<Player[]>([]);const [player,setPlayer]=useState<Player|null>(null);
 const [teams,setTeams]=useState<Team[]>([]);const [teamQuery,setTeamQuery]=useState('');const [level,setLevel]=useState('all');const [selectedTeam,setSelectedTeam]=useState<Team|null>(null);
 const [organizationQuery,setOrganizationQuery]=useState('');const [organization,setOrganization]=useState<Team|null>(null);
 const [report,setReport]=useState<Report|null>(null);const [tab,setTab]=useState('periods');const [filter,setFilter]=useState('');
 const summary=report?summarize(report.games):null;
 const visibleGames=report?.games.filter(g=>`${g.city} ${g.state} ${g.country} ${g.team}`.toLowerCase().includes(filter.toLowerCase()))??[];
 const organizations=teams.filter(t=>t.sportId===1&&t.name.toLowerCase().includes(organizationQuery.toLowerCase())).slice(0,30);
 const affiliates=organization?teams.filter(t=>t.id===organization.id||t.parentOrgId===organization.id).sort((a,b)=>a.sportId-b.sportId||a.name.localeCompare(b.name)):[];
 async function task(name:string,work:()=>Promise<void>){setError('');setBusy(name);try{await work();}catch(e){setError(e instanceof Error?e.message:'Request failed.');}finally{setBusy('');}}
 async function loadTeams(year=season){await task('Loading teams',async()=>setTeams((await getJson(`/api/teams?season=${year}`)).teams));}
 function changeMode(next:'player'|'team'){setMode(next);setTab(next==='team'?'games':'periods');setReport(null);setError('');if(next==='team'&&!teams.length)void loadTeams();}
 function changeSeason(year:number){setSeason(year);setReport(null);setSelectedTeam(null);setOrganization(null);setOrganizationQuery('');setTeamQuery('');setTeams([]);if(mode==='team')void loadTeams(year);}
 async function run(){await task('Building report',async()=>{const body={mode,season,playerId:player?.id,label:mode==='player'?player?.name:selectedTeam?.name,teamSchedule:mode==='team',assignments:mode==='team'&&selectedTeam?[{teamId:selectedTeam.id,teamName:selectedTeam.name,sportId:selectedTeam.sportId,start:`${season}-01-01`,end:`${season}-12-31`,rosterStatus:'Roster assignment'}]:[]};setReport(await getJson('/api/report',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}));setFilter('');});}
 async function exportExcel(){if(!report)return;await task('Exporting',async()=>{const {exportWorkbook}=await import('@/lib/export');await exportWorkbook(report);});}
 const ready=mode==='player'?!!player:!!selectedTeam;
 return <div className="shell">
  <aside className="sidebar"><a href="/" className="brand"><span className="brand-wordmark"><span className="brand-name">C<span className="brand-o">O</span>RE WEALTH</span><span className="brand-subtitle">BASEBALL</span></span></a><nav className="sidebar-tabs"><button disabled={!!busy} className={mode==='player'?'active':''} onClick={()=>changeMode('player')}>Player</button><button disabled={!!busy} className={mode==='team'?'active':''} onClick={()=>changeMode('team')}>Team</button></nav></aside>
  <main><section className="intro"><h1>{mode==='player'?'Player game locations':'Team schedule and locations'}</h1><p>{mode==='player'?'Look up a player to see roster periods, team game locations, dates, and number of games.':'Search an organization to choose an affiliate, or search any team directly.'}</p></section>
   <div className="workspace"><section className="builder card"><div className="section-heading"><span className="step">01</span><h2>{mode==='player'?'Player settings':'Team settings'}</h2></div><label>Tax year<select value={season} disabled={!!busy} onChange={e=>changeSeason(+e.target.value)}>{Array.from({length:Math.max(1,new Date().getFullYear()-2019)},(_,i)=>new Date().getFullYear()+1-i).map(y=><option key={y}>{y}</option>)}</select></label>
    {mode==='player'?<><form onSubmit={e=>{e.preventDefault();setPlayer(null);setReport(null);void task('Searching players',async()=>setPlayers((await getJson(`/api/players?q=${encodeURIComponent(query)}`)).players));}}><label>Player name<div className="search-row"><input value={query} onChange={e=>{setQuery(e.target.value);setPlayer(null);}} placeholder="e.g. Aaron Judge" minLength={2} required/><button className="search-button" disabled={!!busy}>Find</button></div></label></form>{players.length>0&&<div className="results">{players.map(item=><button key={item.id} className={player?.id===item.id?'selected':''} onClick={()=>{setPlayer(item);setReport(null);}}><strong>{item.name}</strong><small>{item.position} · Born {item.birthDate??'unknown'} · ID {item.id}</small></button>)}</div>}</>:
    <><div className="team-search-block"><label>Organization<input value={organizationQuery} onChange={e=>{setOrganizationQuery(e.target.value);setOrganization(null);setSelectedTeam(null);setReport(null);}} placeholder="Search an MLB organization"/></label>{organizationQuery&&!organization&&<div className="results">{organizations.map(org=><button key={org.id} onClick={()=>{setOrganization(org);setOrganizationQuery(org.name);setSelectedTeam(null);setTeamQuery('');setReport(null);}}><strong>{org.name}</strong><small>MLB organization</small></button>)}</div>}{organization&&<div className="affiliate-results"><p className="affiliate-heading">{organization.name} organization</p>{affiliates.map(team=><button key={team.id} className={selectedTeam?.id===team.id?'selected':''} onClick={()=>{setSelectedTeam(team);setTeamQuery(team.name);setReport(null);}}><strong>{team.name}</strong><small>{team.level}{team.league?` · ${team.league}`:''}</small></button>)}</div>}</div>
    <div className="search-divider"><span>or search any team</span></div><label>Level<select value={level} onChange={e=>{setLevel(e.target.value);setSelectedTeam(null);setReport(null);}}><option value="all">All levels</option>{Object.entries(levels).map(([id,name])=><option value={id} key={id}>{name}</option>)}</select></label><label>Team name<input value={teamQuery} onChange={e=>{setTeamQuery(e.target.value);setSelectedTeam(null);setReport(null);}} placeholder="Search MLB or MiLB teams"/></label>{teamQuery&&!selectedTeam&&<div className="results">{teams.filter(t=>(level==='all'||t.sportId===+level)&&t.name.toLowerCase().includes(teamQuery.toLowerCase())).slice(0,40).map(team=><button key={team.id} onClick={()=>{setSelectedTeam(team);setTeamQuery(team.name);setReport(null);}}><strong>{team.name}</strong><small>{team.level} · {team.league}</small></button>)}</div>}{!teams.length&&<button className="text-button" onClick={()=>void loadTeams()}>Reload team directory</button>}<p className="hint">Select an organization to view its affiliates, or search any team directly.</p></>}
    <button className="primary full" disabled={!!busy||!ready} onClick={()=>void run()}>{busy||(mode==='player'?'View player report':'View team schedule')}</button><p className="refresh-note">Records update each time you generate a report.</p></section>
    <section className="report-area">{error&&<div className="error">{error}</div>}{!report?<div className="empty card"><h2>{mode==='player'?'Select a player':'Select a team'}</h2><p>{mode==='player'?'View date periods, cities, states, and game counts.':'View completed games, ballparks, and locations.'}</p></div>:<>
     <div className="report-heading"><div><h2>{report.label}</h2><small>{report.season} · {mode==='team'?'Team schedule':'Roster-based team locations'}</small>{mode==='player'&&report.profileUrl&&<a className="profile-link" href={report.profileUrl} target="_blank" rel="noreferrer">Official player profile</a>}</div><button className="primary" onClick={()=>void exportExcel()}>Export Excel</button></div>
     <div className="metrics"><div><span>Games</span><strong>{report.games.length}</strong></div><div><span>Game dates</span><strong>{summary?.days}</strong></div><div><span>States / provinces</span><strong>{summary?.regions.length}</strong></div><div><span>{mode==='team'?'Ballparks':'Location periods'}</span><strong>{mode==='team'?new Set(report.games.map(g=>g.venue)).size:summary?.periods.length}</strong></div></div>
     {mode==='player'&&report.assignments.some(a=>a.rosterStatus==='Manual review')&&<div className="manual-review-panel"><strong>Manual review</strong>{report.assignments.filter(a=>a.rosterStatus==='Manual review').map((a,i)=><span key={i}>{a.start} through {a.end} · {a.teamName}</span>)}</div>}
     <div className="card report-card"><div className="report-toolbar"><div className="tabs">{(mode==='team'?[['games','Game schedule'],['periods','Location periods'],['regions','By state']]:[['periods','Location periods'],['regions','By state'],['games','Game detail']]).map(([id,name])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{name}</button>)}</div><button className="text-button" onClick={()=>void run()}>Refresh</button></div>{!report.games.length?<div className="no-data">No completed games returned.</div>:<><div className="table-scroll"><table><thead><tr>{(tab==='periods'?['Date period','City','State / province','Team','Games']:tab==='regions'?['State / province','Country','Games','Game dates']:['Date','Team / level','Ballpark / opponent','City / state','Status']).map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{tab==='periods'?summary?.periods.map((p,i)=><tr key={i}><td>{p.start}<small>{p.end!==p.start?`through ${p.end}`:'1 game date'}</small></td><td>{p.city}<small>{p.country}</small></td><td>{p.state}</td><td>{p.team}{p.rosterStatus==='Injured list'&&<small>Injured list</small>}</td><td>{p.games}</td></tr>):tab==='regions'?summary?.regions.map((r,i)=><tr key={i}><td>{r.state}</td><td>{r.country}</td><td>{r.games}</td><td>{r.days}</td></tr>):visibleGames.map(g=><tr key={g.id}><td>{g.date}<small>{g.homeAway}</small></td><td>{g.team}<small>{g.level}</small></td><td>{g.venue}<small>vs. {g.opponent}</small></td><td>{g.city}<small>{g.state} · {g.country}</small></td><td>{mode==='team'?g.status:g.rosterStatus==='Injured list'?'Injured list':'Roster record'}</td></tr>)}</tbody></table></div></>}<div className="report-footer"><span>Updated {new Date(report.retrievedAt).toLocaleString()}</span><span>Through {report.cutoff}</span></div></div>
     {mode==='player'&&<details className="card injury-summary"><summary>Injured-list periods ({report.injuries.length})</summary>{report.injuries.map((item,i)=><div className="timeline-line injury-line" key={i}><strong>{item.team}</strong><span>{item.start} through {item.end}</span><small>{item.status}</small></div>)}</details>}</>}</section>
   </div><footer><strong>CORE Wealth Baseball</strong><span>Team game locations during roster periods.</span></footer></main>
 </div>;
}
